New citation to:
First Sagittarius A* Event Horizon Telescope Results. I. The Shadow of the Supermassive Black Hole in the Center of the Milky Way
by: Rocha, Gabriel S. et al. - Theories of Relativistic Dissipative Fluid Dynamics
https://ui.adsabs.harvard.edu/abs/2023arXiv231115063R

New citation to:
First Sagittarius A* Event Horizon Telescope Results. I. The Shadow of the Supermassive Black Hole in the Center of the Milky Way
by: Raza, Muhammad Ali et al. - Shadow of novel rotating black holes in GR coupled to nonlinear electrodynamics and constraints from EHT results
https://ui.adsabs.harvard.edu/abs/2023arXiv231115784R

New citation to:
First Sagittarius A* Event Horizon Telescope Results. I. The Shadow of the Supermassive Black Hole in the Center of the Milky Way
by: Belkhadria, Zakaria et al. - Mixed scalarization of charged black holes: from spontaneous to non-linear scalarization
https://ui.adsabs.harvard.edu/abs/2023arXiv231115850B

New citation to:
First Sagittarius A* Event Horizon Telescope Results. I. The Shadow of the Supermassive Black Hole in the Center of the Milky Way
by: Hioki, Kenta et al. - Determining parameters of Kerr black holes at finite distance by shadow observation
https://ui.adsabs.harvard.edu/abs/2023arXiv231116802H

New citation to:
First Sagittarius A* Event Horizon Telescope Results. V. Testing Astrophysical Models of the Galactic Center Black Hole
by: Hioki, Kenta et al. - Determining parameters of Kerr black holes at finite distance by shadow observation
https://ui.adsabs.harvard.edu/abs/2023arXiv231116802H

New citation to:
First M87 Event Horizon Telescope Results. VIII. Magnetic Field Structure near The Event Horizon
by: Shen, Ye et al. - Imaging a Semi-Analytical Jet model Generated by 3D GRMHD Simulation
https://ui.adsabs.harvard.edu/abs/2023arXiv231114954S

New citation to:
First M87 Event Horizon Telescope Results. VIII. Magnetic Field Structure near The Event Horizon
by: Hioki, Kenta et al. - Determining parameters of Kerr black holes at finite distance by shadow observation
https://ui.adsabs.harvard.edu/abs/2023arXiv231116802H

New citation to:
First M87 Event Horizon Telescope Results. VII. Polarization of the Ring
by: Hioki, Kenta et al. - Determining parameters of Kerr black holes at finite distance by shadow observation
https://ui.adsabs.harvard.edu/abs/2023arXiv231116802H

New citation to:
First Sagittarius A* Event Horizon Telescope Results. VI. Testing the Black Hole Metric
by: Heidari, N. et al. - Gravitational signatures of a non--commutative stable black hole
https://ui.adsabs.harvard.edu/abs/2023arXiv230506838H

New citation to:
First Sagittarius A* Event Horizon Telescope Results. VI. Testing the Black Hole Metric
by: Zi, Tieguang et al. - Detecting the tidal heating with the generic extreme-mass-ratio inspirals
https://ui.adsabs.harvard.edu/abs/2023arXiv231115532Z

New citation to:
First Sagittarius A* Event Horizon Telescope Results. VI. Testing the Black Hole Metric
by: Raza, Muhammad Ali et al. - Shadow of novel rotating black holes in GR coupled to nonlinear electrodynamics and constraints from EHT results
https://ui.adsabs.harvard.edu/abs/2023arXiv231115784R

New citation to:
First Sagittarius A* Event Horizon Telescope Results. VI. Testing the Black Hole Metric
by: Hioki, Kenta et al. - Determining parameters of Kerr black holes at finite distance by shadow observation
https://ui.adsabs.harvard.edu/abs/2023arXiv231116802H

New citation to:
First Sagittarius A* Event Horizon Telescope Results. III. Imaging of the Galactic Center Supermassive Black Hole
by: Hioki, Kenta et al. - Determining parameters of Kerr black holes at finite distance by shadow observation
https://ui.adsabs.harvard.edu/abs/2023arXiv231116802H

New citation to:
First Sagittarius A* Event Horizon Telescope Results. II. EHT and Multiwavelength Observations, Data Processing, and Calibration
by: Hioki, Kenta et al. - Determining parameters of Kerr black holes at finite distance by shadow observation
https://ui.adsabs.harvard.edu/abs/2023arXiv231116802H

New citation to:
First Sagittarius A* Event Horizon Telescope Results. IV. Variability, Morphology, and Black Hole Mass
by: Raza, Muhammad Ali et al. - Shadow of novel rotating black holes in GR coupled to nonlinear electrodynamics and constraints from EHT results
https://ui.adsabs.harvard.edu/abs/2023arXiv231115784R

New citation to:
First Sagittarius A* Event Horizon Telescope Results. IV. Variability, Morphology, and Black Hole Mass
by: Hioki, Kenta et al. - Determining parameters of Kerr black holes at finite distance by shadow observation
https://ui.adsabs.harvard.edu/abs/2023arXiv231116802H

New citation to:
Constraints on black-hole charges with the 2017 EHT observations of M87*
by: Hioki, Kenta et al. - Determining parameters of Kerr black holes at finite distance by shadow observation
https://ui.adsabs.harvard.edu/abs/2023arXiv231116802H

New citation to:
WISDOM project - XI. Star formation efficiency in the bulge of the AGN-host Galaxy NGC 3169 with SITELLE and ALMA
by: Liang, Fu-Heng et al. - WISDOM project -- XVIII. Molecular gas distributions and kinematics of three megamaser galaxies
https://ui.adsabs.harvard.edu/abs/2023arXiv231115447L

