New citation to:
Searching for continuous Gravitational Waves in the second data release of the International Pulsar Timing Array
by: Chen, Zu-Cheng et al. - Search for Non-Tensorial Gravitational-Wave Backgrounds in the NANOGrav 15-Year Data Set
https://ui.adsabs.harvard.edu/abs/2023arXiv231011238C

New citation to:
The International Pulsar Timing Array: second data release
by: Yin, He et al. - Pulsar Based Alternative Timing Source for Grid Synchronization and Operation
https://ui.adsabs.harvard.edu/abs/2020IEEEA...8n7818Y

New citation to:
The second data release from the European Pulsar Timing Array. III. Search for gravitational wave signals
by: Ghosh, Purusottam et al. - Interplay among gravitational waves, dark matter and collider signals in the singlet scalar extended type-II seesaw model
https://ui.adsabs.harvard.edu/abs/2022arXiv221115640G

New citation to:
The second data release from the European Pulsar Timing Array. III. Search for gravitational wave signals
by: Guo, Huai-Ke - Dissipative Effects as New Observables for Cosmological Phase Transitions
https://ui.adsabs.harvard.edu/abs/2023arXiv231010927G

New citation to:
The second data release from the European Pulsar Timing Array. III. Search for gravitational wave signals
by: Choudhury, Sayantan et al. - Primordial non-Gaussianity as a saviour for PBH overproduction in SIGWs generated by Pulsar Timing Arrays for Galileon inflation
https://ui.adsabs.harvard.edu/abs/2023arXiv231011034C

New citation to:
The second data release from the European Pulsar Timing Array. III. Search for gravitational wave signals
by: Chen, Zu-Cheng et al. - Search for Non-Tensorial Gravitational-Wave Backgrounds in the NANOGrav 15-Year Data Set
https://ui.adsabs.harvard.edu/abs/2023arXiv231011238C

New citation to:
The second data release from the European Pulsar Timing Array. III. Search for gravitational wave signals
by: Nassiri-Rad, Amin et al. - Induced Gravitational Waves from Non-attractor Inflation and NANOGrav data
https://ui.adsabs.harvard.edu/abs/2023arXiv231011427N

New citation to:
The second data release from the European Pulsar Timing Array. I. The dataset and timing analysis
by: Choudhury, Sayantan et al. - Primordial non-Gaussianity as a saviour for PBH overproduction in SIGWs generated by Pulsar Timing Arrays for Galileon inflation
https://ui.adsabs.harvard.edu/abs/2023arXiv231011034C

New citation to:
The second data release from the European Pulsar Timing Array. I. The dataset and timing analysis
by: Chen, Zu-Cheng et al. - Search for Non-Tensorial Gravitational-Wave Backgrounds in the NANOGrav 15-Year Data Set
https://ui.adsabs.harvard.edu/abs/2023arXiv231011238C

New citation to:
The second data release from the European Pulsar Timing Array. II. Customised pulsar noise models for spatially correlated gravitational waves
by: Choudhury, Sayantan et al. - Primordial non-Gaussianity as a saviour for PBH overproduction in SIGWs generated by Pulsar Timing Arrays for Galileon inflation
https://ui.adsabs.harvard.edu/abs/2023arXiv231011034C

New citation to:
The second data release from the European Pulsar Timing Array: V. Implications for massive black holes, dark matter and the early Universe
by: Guo, Huai-Ke - Dissipative Effects as New Observables for Cosmological Phase Transitions
https://ui.adsabs.harvard.edu/abs/2023arXiv231010927G

New citation to:
The second data release from the European Pulsar Timing Array: V. Implications for massive black holes, dark matter and the early Universe
by: Choudhury, Sayantan et al. - Primordial non-Gaussianity as a saviour for PBH overproduction in SIGWs generated by Pulsar Timing Arrays for Galileon inflation
https://ui.adsabs.harvard.edu/abs/2023arXiv231011034C

New citation to:
The second data release from the European Pulsar Timing Array: V. Implications for massive black holes, dark matter and the early Universe
by: Chen, Zu-Cheng et al. - Search for Non-Tensorial Gravitational-Wave Backgrounds in the NANOGrav 15-Year Data Set
https://ui.adsabs.harvard.edu/abs/2023arXiv231011238C

New citation to:
The second data release from the European Pulsar Timing Array: V. Implications for massive black holes, dark matter and the early Universe
by: Nassiri-Rad, Amin et al. - Induced Gravitational Waves from Non-attractor Inflation and NANOGrav data
https://ui.adsabs.harvard.edu/abs/2023arXiv231011427N

New citation to:
The second data release from the European Pulsar Timing Array IV. Search for continuous gravitational wave signals
by: Choudhury, Sayantan et al. - Primordial non-Gaussianity as a saviour for PBH overproduction in SIGWs generated by Pulsar Timing Arrays for Galileon inflation
https://ui.adsabs.harvard.edu/abs/2023arXiv231011034C

New citation to:
The second data release from the European Pulsar Timing Array: VI. Challenging the ultralight dark matter paradigm
by: Choudhury, Sayantan et al. - Primordial non-Gaussianity as a saviour for PBH overproduction in SIGWs generated by Pulsar Timing Arrays for Galileon inflation
https://ui.adsabs.harvard.edu/abs/2023arXiv231011034C

