New citation to:
The NANOGrav 12.5 yr Data Set: Search for an Isotropic Stochastic Gravitational-wave Background
by: Borah, Debasish et al. - Imprint of PBH domination on gravitational waves generated by cosmic strings
https://ui.adsabs.harvard.edu/abs/2023arXiv230411844B

