New citation to:
The NANOGrav 15 yr Data Set: Evidence for a Gravitational-wave Background
by: Compère, Geoffrey et al. - Quadrupolar radiation in de Sitter: displacement memory and Bondi metric
https://ui.adsabs.harvard.edu/abs/2024CQGra..41o5006C

New citation to:
The NANOGrav 15 yr Data Set: Evidence for a Gravitational-wave Background
by: Giarè, William - Inflation, the Hubble tension, and early dark energy: An alternative overview
https://ui.adsabs.harvard.edu/abs/2024PhRvD.109l3545G

New citation to:
The NANOGrav 15 yr Data Set: Evidence for a Gravitational-wave Background
by: Ianniccari, Andrea et al. - Primordial black hole abundance: The importance of broadness
https://ui.adsabs.harvard.edu/abs/2024PhRvD.109l3549I

New citation to:
The NANOGrav 15 yr Data Set: Evidence for a Gravitational-wave Background
by: Huang, Hai-Long et al. - Toward supermassive primordial black holes from inflationary bubbles
https://ui.adsabs.harvard.edu/abs/2024PhRvD.110b3501H

New citation to:
The NANOGrav 15 yr Data Set: Evidence for a Gravitational-wave Background
by: Grüber, D. et al. - Stochastic gravitational wave background generated by domain wall networks
https://ui.adsabs.harvard.edu/abs/2024PhRvD.110b3505G

New citation to:
The NANOGrav 15 yr Data Set: Evidence for a Gravitational-wave Background
by: Shih, David et al. - Fast Parameter Inference on Pulsar Timing Arrays with Normalizing Flows
https://ui.adsabs.harvard.edu/abs/2024PhRvL.133a1402S

New citation to:
The NANOGrav 15 yr Data Set: Evidence for a Gravitational-wave Background
by: Lamb, William G. et al. - Spectral Variance in a Stochastic Gravitational Wave Background From a Binary Population
https://ui.adsabs.harvard.edu/abs/2024arXiv240706270L

New citation to:
The NANOGrav 15 yr Data Set: Evidence for a Gravitational-wave Background
by: Montano, Federico et al. - Detecting Relativistic Doppler by Multi-Tracing a Single Galaxy Population
https://ui.adsabs.harvard.edu/abs/2024arXiv240706284M

New citation to:
The NANOGrav 15 yr Data Set: Evidence for a Gravitational-wave Background
by: Donlon, Thomas, II et al. - The Anomalous Acceleration of PSR J2043+1711: Long-Period Orbital Companion or Stellar Flyby?
https://ui.adsabs.harvard.edu/abs/2024arXiv240706482D

New citation to:
The NANOGrav 15 yr Data Set: Evidence for a Gravitational-wave Background
by: Reardon, Daniel J. et al. - The neutron star mass, distance, and inclination from precision timing of the brilliant millisecond pulsar J0437$-$4715
https://ui.adsabs.harvard.edu/abs/2024arXiv240707132R

New citation to:
The NANOGrav 15 yr Data Set: Evidence for a Gravitational-wave Background
by: Bhattacharyya, Arpan et al. - Bootstrapping spinning two body problem in dynamical Chern-Simons gravity using worldline QFT
https://ui.adsabs.harvard.edu/abs/2024arXiv240707195B

New citation to:
The NANOGrav 15 yr Data Set: Evidence for a Gravitational-wave Background
by: Wu, Yu-Mei et al. - The spatial correlations between pulsars for interfering sources in Pulsar Timing Array and evidence for gravitational-wave background in NANOGrav 15-year data set
https://ui.adsabs.harvard.edu/abs/2024arXiv240707319W

New citation to:
The NANOGrav 15 yr Data Set: Evidence for a Gravitational-wave Background
by: Sojka, Bartosz et al. - Radiative symmetry breaking from the on-shell perspective
https://ui.adsabs.harvard.edu/abs/2024arXiv240707437S

New citation to:
The NANOGrav 15 yr Data Set: Evidence for a Gravitational-wave Background
by: Lemke, Anna-Malin et al. - Detecting Gravitational Wave Anisotropies from Supermassive Black Hole Binaries
https://ui.adsabs.harvard.edu/abs/2024arXiv240708705L

New citation to:
The NANOGrav 15 yr Data Set: Constraints on Supermassive Black Hole Binaries from the Gravitational-wave Background
by: Shih, David et al. - Fast Parameter Inference on Pulsar Timing Arrays with Normalizing Flows
https://ui.adsabs.harvard.edu/abs/2024PhRvL.133a1402S

New citation to:
The NANOGrav 15 yr Data Set: Constraints on Supermassive Black Hole Binaries from the Gravitational-wave Background
by: Lamb, William G. et al. - Spectral Variance in a Stochastic Gravitational Wave Background From a Binary Population
https://ui.adsabs.harvard.edu/abs/2024arXiv240706270L

New citation to:
The NANOGrav 15 yr Data Set: Constraints on Supermassive Black Hole Binaries from the Gravitational-wave Background
by: Wu, Yu-Mei et al. - The spatial correlations between pulsars for interfering sources in Pulsar Timing Array and evidence for gravitational-wave background in NANOGrav 15-year data set
https://ui.adsabs.harvard.edu/abs/2024arXiv240707319W

New citation to:
The NANOGrav 15 yr Data Set: Constraints on Supermassive Black Hole Binaries from the Gravitational-wave Background
by: Lemke, Anna-Malin et al. - Detecting Gravitational Wave Anisotropies from Supermassive Black Hole Binaries
https://ui.adsabs.harvard.edu/abs/2024arXiv240708705L

New citation to:
The NANOGrav 15 yr Data Set: Search for Signals from New Physics
by: Giarè, William - Inflation, the Hubble tension, and early dark energy: An alternative overview
https://ui.adsabs.harvard.edu/abs/2024PhRvD.109l3545G

New citation to:
The NANOGrav 15 yr Data Set: Search for Signals from New Physics
by: Grüber, D. et al. - Stochastic gravitational wave background generated by domain wall networks
https://ui.adsabs.harvard.edu/abs/2024PhRvD.110b3505G

New citation to:
The NANOGrav 15 yr Data Set: Search for Signals from New Physics
by: Shih, David et al. - Fast Parameter Inference on Pulsar Timing Arrays with Normalizing Flows
https://ui.adsabs.harvard.edu/abs/2024PhRvL.133a1402S

New citation to:
The NANOGrav 15 yr Data Set: Search for Signals from New Physics
by: Lamb, William G. et al. - Spectral Variance in a Stochastic Gravitational Wave Background From a Binary Population
https://ui.adsabs.harvard.edu/abs/2024arXiv240706270L

New citation to:
The NANOGrav 15 yr Data Set: Search for Signals from New Physics
by: Lemke, Anna-Malin et al. - Detecting Gravitational Wave Anisotropies from Supermassive Black Hole Binaries
https://ui.adsabs.harvard.edu/abs/2024arXiv240708705L

New citation to:
The NANOGrav 12.5 yr Data Set: Search for an Isotropic Stochastic Gravitational-wave Background
by: Sato-Polito, Gabriela et al. - Exploring the spectrum of stochastic gravitational-wave anisotropies with pulsar timing arrays
https://ui.adsabs.harvard.edu/abs/2024PhRvD.109l3544S

New citation to:
The NANOGrav 12.5 yr Data Set: Search for an Isotropic Stochastic Gravitational-wave Background
by: Shih, David et al. - Fast Parameter Inference on Pulsar Timing Arrays with Normalizing Flows
https://ui.adsabs.harvard.edu/abs/2024PhRvL.133a1402S

New citation to:
The NANOGrav 12.5 yr Data Set: Search for an Isotropic Stochastic Gravitational-wave Background
by: Cai, Yong et al. - Primordial Black Holes from Null Energy Condition Violation during Inflation
https://ui.adsabs.harvard.edu/abs/2024PhRvL.133b1001C

New citation to:
The NANOGrav 15 yr Data Set: Observations and Timing of 68 Millisecond Pulsars
by: Donlon, Thomas, II et al. - The Anomalous Acceleration of PSR J2043+1711: Long-Period Orbital Companion or Stellar Flyby?
https://ui.adsabs.harvard.edu/abs/2024arXiv240706482D

New citation to:
The NANOGrav 15 yr Data Set: Observations and Timing of 68 Millisecond Pulsars
by: Wu, Yu-Mei et al. - The spatial correlations between pulsars for interfering sources in Pulsar Timing Array and evidence for gravitational-wave background in NANOGrav 15-year data set
https://ui.adsabs.harvard.edu/abs/2024arXiv240707319W

New citation to:
The NANOGrav 15 yr Data Set: Observations and Timing of 68 Millisecond Pulsars
by: Lemke, Anna-Malin et al. - Detecting Gravitational Wave Anisotropies from Supermassive Black Hole Binaries
https://ui.adsabs.harvard.edu/abs/2024arXiv240708705L

New citation to:
The NANOGrav 15 yr Data Set: Bayesian Limits on Gravitational Waves from Individual Supermassive Black Hole Binaries
by: Lemke, Anna-Malin et al. - Detecting Gravitational Wave Anisotropies from Supermassive Black Hole Binaries
https://ui.adsabs.harvard.edu/abs/2024arXiv240708705L

New citation to:
The NANOGrav 15 yr Data Set: Search for Anisotropy in the Gravitational-wave Background
by: Lamb, William G. et al. - Spectral Variance in a Stochastic Gravitational Wave Background From a Binary Population
https://ui.adsabs.harvard.edu/abs/2024arXiv240706270L

New citation to:
The NANOGrav 15 yr Data Set: Search for Anisotropy in the Gravitational-wave Background
by: Lemke, Anna-Malin et al. - Detecting Gravitational Wave Anisotropies from Supermassive Black Hole Binaries
https://ui.adsabs.harvard.edu/abs/2024arXiv240708705L

New citation to:
The International Pulsar Timing Array second data release: Search for an isotropic gravitational wave background
by: Sato-Polito, Gabriela et al. - Exploring the spectrum of stochastic gravitational-wave anisotropies with pulsar timing arrays
https://ui.adsabs.harvard.edu/abs/2024PhRvD.109l3544S

New citation to:
The NANOGrav 15 yr Data Set: Detector Characterization and Noise Budget
by: Donlon, Thomas, II et al. - The Anomalous Acceleration of PSR J2043+1711: Long-Period Orbital Companion or Stellar Flyby?
https://ui.adsabs.harvard.edu/abs/2024arXiv240706482D

New citation to:
The NANOGrav 15 yr Data Set: Detector Characterization and Noise Budget
by: Reardon, Daniel J. et al. - The neutron star mass, distance, and inclination from precision timing of the brilliant millisecond pulsar J0437$-$4715
https://ui.adsabs.harvard.edu/abs/2024arXiv240707132R

New citation to:
The NANOGrav 15 yr Data Set: Detector Characterization and Noise Budget
by: Wu, Yu-Mei et al. - The spatial correlations between pulsars for interfering sources in Pulsar Timing Array and evidence for gravitational-wave background in NANOGrav 15-year data set
https://ui.adsabs.harvard.edu/abs/2024arXiv240707319W

New citation to:
The astrophysics of nanohertz gravitational waves
by: Lamb, William G. et al. - Spectral Variance in a Stochastic Gravitational Wave Background From a Binary Population
https://ui.adsabs.harvard.edu/abs/2024arXiv240706270L

New citation to:
The astrophysics of nanohertz gravitational waves
by: Wu, Yu-Mei et al. - The spatial correlations between pulsars for interfering sources in Pulsar Timing Array and evidence for gravitational-wave background in NANOGrav 15-year data set
https://ui.adsabs.harvard.edu/abs/2024arXiv240707319W

New citation to:
The NANOGrav 15 yr Data Set: Looking for Signs of Discreteness in the Gravitational-wave Background
by: Lamb, William G. et al. - Spectral Variance in a Stochastic Gravitational Wave Background From a Binary Population
https://ui.adsabs.harvard.edu/abs/2024arXiv240706270L

New citation to:
The NANOGrav 15 yr Data Set: Looking for Signs of Discreteness in the Gravitational-wave Background
by: Wu, Yu-Mei et al. - The spatial correlations between pulsars for interfering sources in Pulsar Timing Array and evidence for gravitational-wave background in NANOGrav 15-year data set
https://ui.adsabs.harvard.edu/abs/2024arXiv240707319W

New citation to:
The NANOGrav 12.5 yr Data Set: A Computationally Efficient Eccentric Binary Search Pipeline and Constraints on an Eccentric Supermassive Binary Candidate in 3C 66B
by: Bhattacharyya, Arpan et al. - Bootstrapping spinning two body problem in dynamical Chern-Simons gravity using worldline QFT
https://ui.adsabs.harvard.edu/abs/2024arXiv240707195B

New citation to:
The NANOGrav 12.5 yr Data Set: Observations and Narrowband Timing of 47 Millisecond Pulsars
by: Shih, David et al. - Fast Parameter Inference on Pulsar Timing Arrays with Normalizing Flows
https://ui.adsabs.harvard.edu/abs/2024PhRvL.133a1402S

New citation to:
The NANOGrav 12.5 yr Data Set: Observations and Narrowband Timing of 47 Millisecond Pulsars
by: Donlon, Thomas, II et al. - The Anomalous Acceleration of PSR J2043+1711: Long-Period Orbital Companion or Stellar Flyby?
https://ui.adsabs.harvard.edu/abs/2024arXiv240706482D

New citation to:
An Unusual Pulse Shape Change Event in PSR J1713+0747 Observed with the Green Bank Telescope and CHIME
by: Reardon, Daniel J. et al. - The neutron star mass, distance, and inclination from precision timing of the brilliant millisecond pulsar J0437$-$4715
https://ui.adsabs.harvard.edu/abs/2024arXiv240707132R

New citation to:
Astrophysics Milestones for Pulsar Timing Array Gravitational-wave Detection
by: Shih, David et al. - Fast Parameter Inference on Pulsar Timing Arrays with Normalizing Flows
https://ui.adsabs.harvard.edu/abs/2024PhRvL.133a1402S

New citation to:
Searching for Gravitational Waves from Cosmological Phase Transitions with the NANOGrav 12.5-Year Dataset
by: Sojka, Bartosz et al. - Radiative symmetry breaking from the on-shell perspective
https://ui.adsabs.harvard.edu/abs/2024arXiv240707437S

New citation to:
Disentangling Multiple Stochastic Gravitational Wave Background Sources in PTA Data Sets
by: Bellie, Darsan S. et al. - Unresolved stochastic background from compact binary mergers detectable by next-generation ground-based gravitational-wave observatories
https://ui.adsabs.harvard.edu/abs/2024PhRvD.110b3006B

New citation to:
Disentangling Multiple Stochastic Gravitational Wave Background Sources in PTA Data Sets
by: Lamb, William G. et al. - Spectral Variance in a Stochastic Gravitational Wave Background From a Binary Population
https://ui.adsabs.harvard.edu/abs/2024arXiv240706270L

