New citation to:
The EAGLE project: simulating the evolution and assembly of galaxies and their environments
by: Arabsalmani, M. et al. - A Comprehensive Study on the Relation between the Metal Enrichment of Ionized and Atomic Gas in Star-forming Galaxies
https://ui.adsabs.harvard.edu/abs/2023ApJ...952...67A

New citation to:
The EAGLE project: simulating the evolution and assembly of galaxies and their environments
by: de Santi, Natalí S. M. et al. - Robust Field-level Likelihood-free Inference with Galaxies
https://ui.adsabs.harvard.edu/abs/2023ApJ...952...69D

New citation to:
The EAGLE project: simulating the evolution and assembly of galaxies and their environments
by: Kwan, Juliana et al. - Galaxy Clustering in the Mira-Titan Universe. I. Emulators for the Redshift Space Galaxy Correlation Function and Galaxy-Galaxy Lensing
https://ui.adsabs.harvard.edu/abs/2023ApJ...952...80K

New citation to:
The EAGLE project: simulating the evolution and assembly of galaxies and their environments
by: Hadzhiyska, Boryana et al. - The MillenniumTNG Project: refining the one-halo model of red and blue galaxies at different redshifts
https://ui.adsabs.harvard.edu/abs/2023MNRAS.524.2524H

New citation to:
The EAGLE project: simulating the evolution and assembly of galaxies and their environments
by: Pakmor, Rüdiger et al. - The MillenniumTNG Project: the hydrodynamical full physics simulation and a first look at its galaxy clusters
https://ui.adsabs.harvard.edu/abs/2023MNRAS.524.2539P

New citation to:
The EAGLE project: simulating the evolution and assembly of galaxies and their environments
by: Bose, Sownak et al. - The MillenniumTNG Project: the large-scale clustering of galaxies
https://ui.adsabs.harvard.edu/abs/2023MNRAS.524.2579B

New citation to:
The EAGLE project: simulating the evolution and assembly of galaxies and their environments
by: Vijayan, Aditi et al. - X-ray emission from the interstellar and circumgalactic medium of elliptical galaxies based on MACER simulations
https://ui.adsabs.harvard.edu/abs/2023MNRAS.tmp.2036V

New citation to:
The EAGLE project: simulating the evolution and assembly of galaxies and their environments
by: Jiménez, Esteban et al. - The physical drivers of gas turbulence in simulated disc galaxies
https://ui.adsabs.harvard.edu/abs/2023MNRAS.tmp.2049J

New citation to:
The EAGLE project: simulating the evolution and assembly of galaxies and their environments
by: Cooray, Suchetha et al. - Characterizing and understanding galaxies with two parameters
https://ui.adsabs.harvard.edu/abs/2023MNRAS.tmp.2069C

New citation to:
The EAGLE simulations of galaxy formation: calibration of subgrid physics and model variations
by: Arabsalmani, M. et al. - A Comprehensive Study on the Relation between the Metal Enrichment of Ionized and Atomic Gas in Star-forming Galaxies
https://ui.adsabs.harvard.edu/abs/2023ApJ...952...67A

New citation to:
The EAGLE simulations of galaxy formation: calibration of subgrid physics and model variations
by: de Santi, Natalí S. M. et al. - Robust Field-level Likelihood-free Inference with Galaxies
https://ui.adsabs.harvard.edu/abs/2023ApJ...952...69D

New citation to:
The EAGLE simulations of galaxy formation: calibration of subgrid physics and model variations
by: Afruni, Andrea et al. - Clouds accreting from the IGM are not able to feed the star formation of low-redshift disc galaxies
https://ui.adsabs.harvard.edu/abs/2023MNRAS.524.2351A

New citation to:
The EAGLE simulations of galaxy formation: calibration of subgrid physics and model variations
by: Jiménez, Esteban et al. - The physical drivers of gas turbulence in simulated disc galaxies
https://ui.adsabs.harvard.edu/abs/2023MNRAS.tmp.2049J

New citation to:
The EAGLE simulations of galaxy formation: Public release of halo and galaxy catalogues
by: Arabsalmani, M. et al. - A Comprehensive Study on the Relation between the Metal Enrichment of Ionized and Atomic Gas in Star-forming Galaxies
https://ui.adsabs.harvard.edu/abs/2023ApJ...952...67A

New citation to:
The EAGLE simulations of galaxy formation: Public release of halo and galaxy catalogues
by: Jiménez, Esteban et al. - The physical drivers of gas turbulence in simulated disc galaxies
https://ui.adsabs.harvard.edu/abs/2023MNRAS.tmp.2049J

New citation to:
The evolution of the barred galaxy population in the TNG50 simulation
by: Dillamore, Adam M. et al. - Stellar halo substructure generated by bar resonances
https://ui.adsabs.harvard.edu/abs/2023MNRAS.tmp.2042D

New citation to:
Evolution of galaxy stellar masses and star formation rates in the EAGLE simulations
by: Jiménez, Esteban et al. - The physical drivers of gas turbulence in simulated disc galaxies
https://ui.adsabs.harvard.edu/abs/2023MNRAS.tmp.2049J

New citation to:
Evolution of galaxy stellar masses and star formation rates in the EAGLE simulations
by: Lohmann, Felipe S. et al. - The origin of massive compact galaxies: Lessons from illustristng
https://ui.adsabs.harvard.edu/abs/2023MNRAS.tmp.2084L

New citation to:
The impact of angular momentum on black hole accretion rates in simulations of galaxy formation
by: Jiménez, Esteban et al. - The physical drivers of gas turbulence in simulated disc galaxies
https://ui.adsabs.harvard.edu/abs/2023MNRAS.tmp.2049J

New citation to:
The evolution of the oxygen abundance gradients in star-forming galaxies in the EAGLE simulations
by: Arabsalmani, M. et al. - A Comprehensive Study on the Relation between the Metal Enrichment of Ionized and Atomic Gas in Star-forming Galaxies
https://ui.adsabs.harvard.edu/abs/2023ApJ...952...67A

New citation to:
The oxygen abundance gradients in the gas discs of galaxies in the EAGLE simulation
by: Arabsalmani, M. et al. - A Comprehensive Study on the Relation between the Metal Enrichment of Ionized and Atomic Gas in Star-forming Galaxies
https://ui.adsabs.harvard.edu/abs/2023ApJ...952...67A

