name: Mail

#on: [push]

on:
  schedule:
    - cron: '0 10 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Prepare Env
      env:
        SECRET_MAIL_PASSWORD: ${{ secrets.SECRET_MAIL_PASSWORD }}
        SECRET_GITHUB_TOKEN: ${{ secrets.SECRET_GITHUB_TOKEN }}
      run: |
        python mail.py
    - name: Send mails
      run: |
        git config --local user.email "michael@jaekle.info"
        git config --local user.name "hippke"
        git add .
        git add --all
        # git commit -m "Add changes" -a
        git diff --quiet && git diff --staged --quiet || git commit -am 'Add changes'
    - name: Push
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: master
