name: reorg
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v1
    - name: Reorg
      run: |
        echo 1
        git config --local user.email "michael@jaekle.info"
        echo 2
        git config --local user.name "hippke"
        git filter-branch --parent-filter '
        read parent
        if [ "$parent" = "-p 1db3642ac91bdc98990cab5f2c62dddad88ebb68" ]
        then
            echo
        else
            echo "$parent"
        fi'
        git update-ref -d refs/original/refs/heads/master
        git reflog expire --expire-unreachable=all --all
        git gc --prune=all
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.SECRET_GITHUB_TOKEN }}
